Import necessary library

In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from pathlib import Path

In [5]:
df = pd.read_csv("../data/processed/spam_classifier_dataset.csv")

In [6]:
df.head(10)

,Subject,Message,Spam/Ham,Date,label,message_len,subject_len,word_count,num_caps,num_digits,num_urls
0,"vastar resources , inc .","gary , production from the high island larger ...",ham,1999-12-13,0,4282,24,1572,0,315,0
1,calpine daily gas nomination,- calpine daily gas nomination 1 . doc,ham,1999-12-14,0,38,28,8,0,1,0
2,re : issue,fyi - see note below - already done .\nstella\...,ham,1999-12-14,0,1171,10,344,0,68,0
3,meter 7268 nov allocation,fyi .\n- - - - - - - - - - - - - - - - - - - -...,ham,1999-12-14,0,1124,25,318,0,55,0
4,mcmullen gas for 11 / 99,"jackie ,\nsince the inlet to 3 river plant is ...",ham,1999-12-14,0,534,24,119,0,19,0
5,meter 1517 - jan 1999,"george ,\ni need the following done :\njan 13\...",ham,1999-12-14,0,411,21,90,0,76,0
6,duns number changes,fyi\n- - - - - - - - - - - - - - - - - - - - -...,ham,1999-12-14,0,1375,19,340,0,146,0
7,king ranch,there are two fields of gas that i am having d...,ham,1999-12-14,0,1616,10,328,0,45,0
8,re : entex transistion,thanks so much for the memo . i would like to ...,ham,1999-12-14,0,3039,22,640,0,28,0
9,entex transistion,the purpose of the email is to recap the kicko...,ham,1999-12-14,0,1734,17,329,0,14,0

In [7]:
df.columns

Index(['Subject', 'Message', 'Spam/Ham', 'Date', 'label', 'message_len',
       'subject_len', 'word_count', 'num_caps', 'num_digits', 'num_urls'],
      dtype='str')

The statistics show missing data for the entire column

In [8]:
df.isna().sum().sort_values(ascending=False)

Subject        0
Message        0
Spam/Ham       0
Date           0
label          0
message_len    0
subject_len    0
word_count     0
num_caps       0
num_digits     0
num_urls       0
dtype: int64

No missing in dataframe

Find the empty/white-space

In [10]:
subj_blank = df['Subject'].isna() | (df["Subject"].str.strip() == "")
date_blank = df["Date"].isna() | (df["Date"].str.strip() == "")
df[subj_blank | date_blank]

Empty DataFrame
Columns: [Subject, Message, Spam/Ham, Date, label, message_len, subject_len, word_count, num_caps, num_digits, num_urls]
Index: []

In [11]:
date_parsed = pd.to_datetime(df["Date"], errors="coerce")  
bad_dates = df[date_parsed.isna()]

In [13]:
dup_mask = df.duplicated(["Subject", "Message"], keep=False)  
dup_count = dup_mask.sum()                                                                                                                                                                                        
df_duplicates = df[dup_mask]

In [16]:
print(df.shape)
print(df_duplicates.shape)

(33664, 11)
(18369, 11)

In [17]:
dup_stats = (
  df.groupby(["Subject","Message"])
   .agg(
     count=("label", "size"),
     label_variants=("label","nunique"),
     spamham_variants=("Spam/Ham","nunique")
   )
   .reset_index()
)

In [24]:
print(dup_stats[dup_stats["spamham_variants"] > 1].shape)
print(dup_stats.shape)

(6, 5)
(15861, 5)